//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Youtility_RestAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int ticket_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string user_name { get; set; }
        public Nullable<int> event_id { get; set; }
        public string action { get; set; }
    
        public virtual Event Event { get; set; }
    }
}
